loc_button_login_in_acaunt=".//button[text()='Войти в аккаунт']"
loc_button_reg="//button[text()='Зарегистрироваться']"
loc_email="//label[text()='Email']/../input"
loc_pass="//label[text()='Пароль']/../input"
loc_name="//label[text()='Имя']/../input"
loc_button_Voiti="//*[@id='root']/div/main/div/form/button"
loc_login_Vhod=".//h2[text()='Вход']"
loc_vostanovit_paroll="//*[@id='root']/div/main/div/div/p[2]/a"
loc_lichni_cabinet="//*[@id='root']/div/header/nav/a/p"
loc_proffil='Профиль'
loc_history_order='История заказов'
loc_out="//*[@id='root']/div/main/div/nav/ul/li[3]/button"
loc_button_login_voiti="//button[text()='Войти']"
loc_vhod="//*[@id='root']/div/main/div/h2"
loc_constructor="//*[@id='root']/div/header/nav/ul/li[1]/a/p"
loc_text_sous="//*[@id='root']/div/main/section[1]/div[2]/h2[2]"
loc_button_sous="//*[@id='root']/div/main/section[1]/div[1]"
loc_button_bulki="//*[@id='root']/div/main/section[1]/div[1]"
loc_text_bulki="//*[@id='root']/div/main/section[1]/div[2]/h2[1]"
loc_text_nachinki="//*[@id='root']/div/main/section[1]/div[2]/h2[3]"
loc_buton_nachinki="//*[@id='root']/div/main/section[1]/div[1]"
loc_linc_reg="//a[text()='Зарегистрироваться']"
loc_error_reg= "input__error text_type_main-default"
loc_button_oformit_zakaz="//*[@id='root']/div/main/section[2]/div/button"
loc_non_correct_pas="//*[@id='root']/div/main/div/form/fieldset[3]/div/p"
loc_test_soberi_burger="//*[@id='root']/div/main/section[1]/h1"
loc_linc_voiti="//*[@id='root']/div/main/div/div/p/a"